print("love story")
boy_name = input("BOY name: ")
boy_age = int(input("Boy age: "))
girl_name = input("Girl name: ")
girl_age = int(input("Girl age: "))
age_diff = abs(boy_age - girl_age)
print(boy_name + " Loves " + girl_name +". Age difference is " + str(age_diff))
print(f"{boy_name} Loves {girl_name}. Age difference is {age_diff}")
